export const NFTs = [
  {
    Id: 1,
    Badge: "1 Month Renting Price: $12 500",
    ImageUrl: "/images/rentings/all.png",
    Edition: 371,
    Stock: 128,
    Title: "One-Day Renting Price",
    Price: "$500",
    Avatar: "/images/avatar/alliance.png",
    Author: "Alliance Group",
    Likes: 1500,
  },
  {
    Id: 2,
    Badge: "6 Month Renting Price: $55 000",
    ImageUrl: "/images/rentings/blox.png",
    Edition: 371,
    Stock: 128,
    Title: "One-Month Renting Price",
    Price: "$10 000",
    Avatar: "/images/avatar/blox.png",
    Author: "BLOX",
    Likes: 652,
  },
  {
    Id: 3,
    Badge: "1 Year Renting Price: $50 000",
    ImageUrl: "/images/rentings/axis.png",
    Edition: 371,
    Stock: 128,
    Title: "One-Month Renting Price",
    Price: "$5 000",
    Avatar: "/images/avatar/aaxis.png",
    Author: "AXIS TOWERS",
    Likes: 652,
  },

];
